DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS articles;

CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    userid VARCHAR(36) NOT NULL,
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE articles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    articleid VARCHAR(36) NOT NULL,
    name VARCHAR(256) NOT NULL,
    description VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    orderid VARCHAR(36) NOT NULL,
    description VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);
